### ISSUE TITLE
looking for examples

### ISSUE THREAD

**Issue by JosephBARBIERDARNAL** [ARundle01/ecmm428-pycart#5]
Hi, I'm working on the python-graph-gallery.com website (https://python-graph-gallery.com) and we're looking to add articles on how to create cartograms in Python.

Your library seems to fit this purpose but I haven't found many examples on how to use it in different situations (actually only the one from the mkdocs website). Do you have any other examples?

Thanks

**Comment by ARundle01** [comment]
Hi Joseph, thanks for your interest in my library! I had intended for the mkdocs to cover the usage of pycart, but coming back to this after a year away I can see it isn't as clear as I had thought 😄 

All the code used to generate images for the [associated dissertation](https://github.com/ARundle01/ecmm428-pycart/blob/dfd11c45537c6a1bf68c9d571bbce7fba96b73c9/ecmm428-pycart-a-library-for-cartogram-generation-in-python-with-acknowledgements.pdf) can be found in [main.py](https://github.com/ARundle01/ecmm428-pycart/blob/dfd11c45537c6a1bf68c9d571bbce7fba96b73c9/main.py); this might provide a little more insight into how I had used it with a real dataset, but I understand that it's not the most readable.

Do you have a particular dataset in mind for displaying on the graph gallery, or what you have in mind for the article in general? I'd be more than happy to take a look and see if I can come up with a more targeted example.

**Comment by JosephBARBIERDARNAL** [comment]
for example I have this dataset about co2 per capita across europe that I'd like to plot:
```python
import geopandas as gpd

data = gpd.read_file('https://raw.githubusercontent.com/JosephBARBIERDARNAL/misc-dataviz/main/country-co2/data.geojson')
```


As for the article, ideally I'd probably write 2 or 3 to go from the simplest use case to an advanced 'real life' chart. Probably something [like this](https://python-graph-gallery.com/web-small-multiple-with-highlights/)

Do you have an idea of the best way to create the cartogram? Also, the posts will probably describe what cartograms are in general

**Comment by ARundle01** [comment]
No worries, this data is actually already formatted perfectly for pycart. I've written a really basic script below that takes your data and plots a simple dorling cartogram (where countries are represented as circles of size proportional to their value field, in this case Co2 per Capita). 

In this case, I'm creating a `Cartogram` object by supplying the dataframe and the headings on which to operate. I can then run the `dorling()` method on the `Cartogram` object, which returns the cartogram as a new dataframe. I then plot the dorling cartogram over the top of the base map of Europe, using GeoDataFrame's built-in `plot()`.

You can follow the same method to generate a non-contiguous cartogram (where the countries are scaled on their centre-point proportional to the value field), by replacing the `dorling()` method with `non_contiguous()`.

```python
    fig, ax = plt.subplots(1)
    ax.axis('equal')
    ax.axis('off')

    gdf = gpd.read_file('https://raw.githubusercontent.com/JosephBARBIERDARNAL/misc-dataviz/main/country-co2/data.geojson')
    gdf['geometry'] = gdf['geometry'].to_crs(crs=3857)

    gdf.plot(color='w', ax=ax, zorder=0, edgecolor='0', linewidth=0.1, legend=False)

    cart = cartogram.Cartogram(gdf, 'co2Capita', 'country', 'geometry')
    dorling = cart.dorling(iterations=100, stop=None)

    dorling.plot(color='w', ax=ax, zorder=0, edgecolor='0', linewidth=0.1, legend=False)

    # Plot Figure
    plt.savefig("./out/testing.png", dpi=1200)
```

If you're looking for the fancier, density-equalizing cartograms like [this](https://gisgeography.com/wp-content/uploads/2016/09/Density-Equalizing-Cartograms-678x340.png), unfortunately I haven't implemented those (yet, depending on if I get time outside of work).

**Comment by ARundle01** [comment]
The image itself looks like this:

![testing](https://github.com/ARundle01/ecmm428-pycart/assets/61236217/8a8bb5cc-cbc6-4b6c-a6bf-570f1d0ed8e1)

**Comment by JosephBARBIERDARNAL** [comment]
Yes, I'm mainly looking for density-equalising cartograms ^^, as in the example below. Thanks for your example though, but it's less in line with what we'd like to add to the python graph gallery

<img width="495" alt="Screenshot 2024-06-14 at 11 48 30" src="https://github.com/ARundle01/ecmm428-pycart/assets/79746670/f289750a-f6ba-49d0-b2e4-fbbace92fcfc">

I have no idea how complex it is to implement? This already exists in R but unfortunately we don't have much in Python

**Comment by ARundle01** [comment]
Yeah, I had tried to implement this previously but had little success. Unfortunately given the amount of time I have outside of work, I won't be able to implement this any time soon.

**Comment by JosephBARBIERDARNAL** [comment]
Completly understand! wish you the best
